#TODO Fully move ot microsoft database
version: "3.8"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - 1433:1433
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      SA_PASSWORD: "password123!"
      ACCEPT_EULA: "Y"

